version: '3'

services:
  nans-mysql:
    image: mysql:latest
    container_name: nans-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - database-network-nanicas

  nans-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nans-phpmyadmin
    environment:
      PMA_HOST: nans-mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3305:80"
    restart: always
    depends_on:
      - nans-mysql
    networks:
      - database-network-nanicas

networks:
  database-network-nanicas:
    driver: bridge
