version: '3'

services:
  mysql-nanicas:
    image: mysql:latest
    container_name: mysql-nanicas
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - database-network-nanicas

  phpmyadmin-nanicas:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-nanicas
    environment:
      PMA_HOST: mysql-nanicas
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3305:80"
    restart: always
    depends_on:
      - mysql-nanicas
    networks:
      - database-network-nanicas

networks:
  database-network-nanicas:
    driver: bridge
